### ISSUE TITLE
Questao 4

### ISSUE THREAD

**Issue by leonardoabadio** [ZXVentures/code-challenge#3]
Caros, boa noite.

No exercicio 4 não consegui entender o que é pedido nas lacunas.

É para simplesmente responder de acordo com as imagens acima das lacunas? Pois a ultima nao indica para completar nada.

Obrigado.

**Comment by flpStrri** [comment]
Hello, LABADIO! What we wanted is the same thing you would get in one of those data visualisation tools, like Tableau or Power BI. On this exercise more specifically on Power BI since it is the tool we mostly use here in ZX-Ventures.
What we expect is what table fields you would put on that sections to have that graph, here are some app UIs that shows that happening:
Tableau:
![viz1-tableau-tutorial-edureka](https://user-images.githubusercontent.com/13003392/38194724-b2c3919c-364f-11e8-9a09-3293342edee7.png)
Power BI:
![5084_siddharth-mehta-2017-tip-19-jtk 005](https://user-images.githubusercontent.com/13003392/38194727-b4ea2a58-364f-11e8-8fab-57c9f1214d30.png)

**Comment by leonardoabadio** [comment]
Ah ok.

Thanks and sorry for the portuguese.

hughs
